### ISSUE TITLE
Hwang, Jae-Gyun

### ISSUE THREAD

**Issue by geoffharcourt** [chadwickbureau/register#20]
UUID: b296a57f-3d62-4c2e-b2f6-2ec2c7ace970
Birthdate: 1987-07-28

MLBAM ID: 666561
http://m.mlb.com/player/666561/jae-gyun-hwang?year=2017&stats=career-r-hitting-minors

KBO ID: 76313
http://eng.koreabaseball.com/Teams/PlayerInfoHitter/Summary.aspx?pcode=76313

**Comment by tturocy** [comment]
Thanks - although these are all picked up automatically and so there's no need to report them seriatim.

**Comment by geoffharcourt** [comment]
No problem. Are the KBO IDs picked up automatically, or just the MLBAM ones? I was wondering because Kang's was missing.

**Comment by tturocy** [comment]
KBO IDs are not included at all.
