### ISSUE TITLE
Pardinho, Eric

### ISSUE THREAD

**Issue by omwah** [chadwickbureau/register#22]
Eric Eiji Taniguchi Pardinho
Born January 5, 2001
https://www.baseball-reference.com/bullpen/Eric_Pardinho

He signed with the Toronto Blue Jays last year. 

Can not find him in the database. Is this a person I just need to wait to show up in other databases that are being scraped?

**Comment by tturocy** [comment]
He has not appeared in a professional game.

We do not scrape other databases.
