### ISSUE TITLE
Missing fangraphs id for some players who debuted in 2020

### ISSUE THREAD

**Issue by kevins230** [chadwickbureau/register#27]
I noticed that there are some players missing their fangraphs id. The ones that I've noticed have all been players who debuted in 2020 (I think - and I'm not sure if there are others). 

Some examples are: 
1. Victor Gonzalez (Dodgers pitcher) 16408
2. Enoli Paredes (Astros pitcher) 20447
3. Anthony Misiewicz (Mariners pitcher) 18152
4. Ryan Thompson (Rays pitcher) 16647

**Comment by lukedesando** [comment]
It's the same for those who debuted in 2021

**Comment by tturocy** [comment]
Please see comment in #28
