### ISSUE TITLE
Missing MLBAM IDs for Rookies

### ISSUE THREAD

**Issue by sisitzky** [chadwickbureau/register#30]
i.e.

Masataka Yoshida
Oscar Colas
Brice Turang
Joey Weimer
etc.

**Comment by tturocy** [comment]
User error.  These are all there.

**Comment by sisitzky** [comment]
Thanks for the quick response, Ted. I actually meant to reference the **missing retro IDs** for these players, my apologies.

**Comment by tturocy** [comment]
They haven't been assigned yet.

**Comment by sisitzky** [comment]
Makes sense, thank you.
